[profile.default]
src = "src"
out = "out"
script = "script"
# libs = ["lib"]
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
arbitrum-sepolia = "https://arbitrum-sepolia.therpc.io"
local = "http://127.0.0.1:8545"
