[profile.default]
src = "src"
out = "out"
libs = ["../../lib", "permit2/lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=../../lib/openzeppelin-contracts/contracts/",
    "solmate/=permit2/lib/solmate/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
local = "http://127.0.0.1:8545"
