[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
sepolia = { key = "JS247SCERMCYHJJ4XBSFHFARMVKCP4VV27" }
