[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
solc_version = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
local = "http://127.0.0.1:8545"
